### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cokemine** [cokemine/nodestatus#109]
~没有这些功能又不是不能用~
- [x] 新增自定义标题、副标题等 API，方便在 Docker 不挂载前端目录的前提下进行基本前端的自定义
- [ ] 重构代码 & 添加测试
- [ ] 可选的三网延迟丢包监控
- [ ] 一个 Material 样式的前端新主题
- [ ] 一个用 Rust 开发的全新的客户端
- [ ] 可以将服务端部署在 Serverless 服务上的新分支，不使用 Websocket，没有掉线通知功能
- [ ] 可选的更多监控功能，如磁盘 IO
- [ ] 可以将 NodeStatus 作为模块使用

不会新增任何服务端可以操控客户端的功能，避免出现安全问题。
